name: build-and-deploy-gpt
on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * TUE"
  push:
    branches: [main]
    paths-ignore:
      - "**/README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/onlydole/gpt-researcher/gpt
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      - name: Set Docker metadata [NextJS]
        id: metanext
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/onlydole/gpt-researcher/gpt-frontend
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into package registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Container Image [GPT Researcher]
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: mode=max
          sbom: true
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onlydole/gpt-researcher-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onlydole/gpt-researcher-cache,mode=max,ignore-error=true

      - name: Build and push Container Image [NextJS]
        uses: docker/build-push-action@v6
        with:
          file: frontend/nextjs/Dockerfile.dev
          context: frontend/nextjs
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.metanext.outputs.tags }}
          labels: ${{ steps.metanext.outputs.labels }}
          provenance: mode=max
          sbom: true
          platforms: linux/amd64
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onlydole/gpt-researcher-frontend-cache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/onlydole/gpt-researcher-frontend-cache,mode=max,ignore-error=true

  deploy-digitalocean:
    name: Deploy to DigitalOcean
    needs: push-ghcr
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: DigitalOcean App Deployment
        uses: digitalocean/app_action@v1.1.6
        with:
          app_name: gpt-researcher
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
